### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by nicolas-graves** [infinitez-one/lfs-s3#18]
Hi! 
I'm glad you could find inspiration for leading this idea further. 
IIUC, your version adds compressing and configuration, is that right ? 
Do you have an idea / benchmark of the space saved with such a compression ? My intuition was that it was not necessary due to git already compressing blobs.

**Comment by kalmard0** [comment]
Hi, thanks for your message!

AFAICT git does not compress local LFS files: https://confluence.atlassian.com/bbkb/lfs-storage-size-is-bigger-than-the-repository-actual-size-after-lfs-migration-1387596818.html - "These files are not compressed, and each version of a binary file is stored independently."

To be honest I haven't actually checked how much compression actually reduces the total size, however in my use-case I'm uploading LFS files to paid storage and the files are persisted forever (e.g. possibly for my lifetime) so every little compressed bit helps. And in terms of up/download speed, on my 10+ year-old development machine, the bottleneck is still bandwidth.

**Comment by nicolas-graves** [comment]
Oh, right, I've forgotten that. In my use case, I actually do compress them in the repo.
I was thinking about archiving mine and recommending yours, I'll have to read the commits, then I'll probably do.
